version: "3.8"

services:
  orders-db:
    container_name: orders-db
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
      - POSTGRES_HOST_AUTH_METHOD=md5