
GET HTTP://127.0.0.1:3000/api/products?limit=-2&page=-2  HTTP/1.1

###
GET HTTP://127.0.0.1:3000/api/products/1 HTTP/1.1

###
POST HTTP://127.0.0.1:3000/api/products HTTP/1.1
Content-Type: application/json

{
    "name":"casco",
    "price":"15.22"
    //"otro":"safasf"
}

###
PATCH HTTP://127.0.0.1:3000/api/products/7  HTTP/1.1
Content-Type: application/json

{
    "name":"mouse",
    "price":"23.22"
}

###
DELETE HTTP://127.0.0.1:3000/api/products/98 HTTP/1.1

###
GET HTTP://127.0.0.1:3000/api/orders/1 HTTP/1.1