
POST http://localhost:3000/api/orders HTTP/1.1
Content-Type: application/json

{
    "items": [
        {
            "productId": 8,
            "quantity": 5,
            "price": 10
        },
        {
            "productId": 9,
            "quantity": 6,
            "price": 20
        }
    ]
}

###
GET http://localhost:3000/api/orders/6a36cc78-7fb7-4c1f-8210-379ccf1ef985 HTTP/1.1

###
GET http://localhost:3000/api/orders/6a36cc78-7fb7-4c1f-8210-379ccf1ef985 HTTP/1.1

###
POST http://localhost:3003/payments/createPaymentsSession HTTP/1.1

###
POST  http://localhost:3003/payments/webhook HTTP/1.1